version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: durvalcrm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: durvalcrm_user
      POSTGRES_PASSWORD: your_strong_password # Troque por uma senha segura
      POSTGRES_DB: durvalcrm_dev
    ports:
      - "5432:5432"
    volumes:
      # Monta o script de inicialização para criar as tabelas
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Volume nomeado para persistir os dados do banco
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: