version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL (sem alterações)
  postgres-db:
    image: postgres:15-alpine
    container_name: durvalcrm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: durvalcrm_user
      POSTGRES_PASSWORD: durvaldev@123 # Troque por uma senha segura
      POSTGRES_DB: durvalcrm_dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - durvalcrm-net

  # Serviço do Keycloak com Healthcheck
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: durvalcrm_keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/themes:/opt/keycloak/themes
    networks:
      - durvalcrm-net
    # Healthcheck para verificar quando o Keycloak está pronto
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

networks:
  durvalcrm-net:
    driver: bridge

volumes:
  pgdata:
    driver: local
  keycloak_data:
    driver: local