name: Backend CI - DurvalCRM API

# Gatilhos: roda em pushes para a branch 'develop' e qualquer branch 'feature/*'
on:
  push:
    branches: [ 'feature/*' ]

jobs:
  # Nome do job
  build-and-test:
    # Máquina virtual que será usada (Ubuntu é padrão e eficiente)
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do código do repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Adiciona cache para as dependências do Maven, acelerando builds futuros
          cache: maven

      # 3. Executa os testes unitários com o Maven Wrapper
      - name: Run unit tests
        run: ./mvnw test

      # 4. Compila e empacota o projeto (pulando os testes, pois já rodaram)
      - name: Package application
        run: ./mvnw package -DskipTests